-- What kind of client a session was started from.
--
-- A stolen token works from anywhere for thirty days, and nothing about a
-- request says who is holding it. This is the cheap half of an answer: a real
-- session is held by one program for its whole life, and a replayed token is
-- almost always presented by a different one.
--
-- Not the address, which is the obvious thing to bind to and the wrong one — a
-- phone changes address walking between two rooms. `src/auth/fingerprint.ts`
-- explains the shape; it is two words, and versions are deliberately absent so
-- a browser updating itself does not sign its user out.
--
-- Empty means unbound, which is what every existing session is on the day this
-- runs. They are not left that way: `requireAuth` fills the column in from the
-- `user_agent` already recorded against the row, so a session created before
-- this is bound to the client it was actually created by rather than to
-- whoever happens to use it next.
ALTER TABLE sessions ADD COLUMN agent_class TEXT NOT NULL DEFAULT '';
